version: '3.7'

services:
  
  seq:
    image: datalust/seq:latest
    
  nosql.data:
    image: mongo
    
  problemas.api:
    image: ${DOCKER_REGISTRY:-sgq}/problemas.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Problemas/Problemas.API/Dockerfile
    depends_on:
      - nosql.data

  webapigw:
    image: ${DOCKER_REGISTRY:-sgq}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - nosql.data
      - problemas.api
      - workflow.api

  workflow.api:
    image: ${DOCKER_REGISTRY:-sgq}/workflow.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Workflow/Workflow.API/Dockerfile
    depends_on:
      - nosql.data
