version: '3.4'

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  nosql.data:
    ports:
      - "27017:27017"  # Important: In a production environment your should remove the external port

  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  problemas.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${SGQ_AZURE_COSMOSDB:-mongodb://nosql.data}
      - Database=ProblemasDb
#     - identityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110. 
#      - IdentityUrlExternal=http://${SGQ_EXTERNAL_DNS_NAME_OR_IP}:5105
#      - EventBusConnection=${SGQ_AZURE_SERVICE_BUS:-rabbitmq}
#      - EventBusUserName=${SGQ_SERVICE_BUS_USERNAME}
#      - EventBusPassword=${SGQ_SERVICE_BUS_PASSWORD}          
#      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
#      - OrchestratorType=${ORCHESTRATOR_TYPE}
#      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5109:80"   # Important: In a production environment your should remove the external port (5109) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).
  

  tstweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44306
    ports:
      - "55592:80"
      - "44306:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  tstapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


