version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine. 
# The SGQ_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like: 
#     SGQ_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.
services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  problemas.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${SGQ_AZURE_COSMOSDB:-mongodb://nosql.data}
      - Database=ProblemasDb
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5109:80"   # The API Gateway redirects and access through the internal port (80).

  webapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ProblemasUrlHC=http://problemas.api/hc
      - WorkflowUrlHC=http://workflow.api/hc
      - IdentityUrlHC=http://identity.api/hc             
    ports:
      - "5202:80"   
    volumes:
      - ./src/ApiGateways/APIGw-Base:${SGQ_OCELOT_VOLUME_SPEC:-/app/configuration}
   

  workflow.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${SGQ_AZURE_COSMOSDB:-mongodb://nosql.data}
      - Database=WorkflowDb
      - UseLoadTest=False
    ports:
      - "5110:80"   # The API Gateway redirects and access through the internal port (80).
  