version: '3.4'

services:
  
  seq:
    image: datalust/seq:latest
    
  nosql.data:
    image: mongo
    
  rabbitmq:
    image: rabbitmq:3-management-alpine

  tstweb:
    image: ${DOCKER_REGISTRY-}tstweb
    build:
      context: .
      dockerfile: TstWeb/Dockerfile

  tstapi:
    image: ${DOCKER_REGISTRY-}tstapi
    build:
      context: .
      dockerfile: TSTAPI/Dockerfile


  problemas.api:
    image: ${DOCKER_REGISTRY-}problemasapi
    build:
      context: .
      dockerfile: src/services/Problems.API/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq


  webshoppingapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: src/APIGateways/OcelotApiGw/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - problemas.api


