version: '3.4'

services:
  tstweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44306
    ports:
      - "55592:80"
      - "44306:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  tstapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

