version: '3.4'

services:
  
  seq:
    image: datalust/seq:latest
    
  nosql.data:
    image: mongo
    
  rabbitmq:
    image: rabbitmq:3-management-alpine

    
  problemas.api:
    image: ${DOCKER_REGISTRY-}problemas.api
    build:
      context: .
      dockerfile: src/Services/Problems.API/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  


